import Head from 'next/head'
import Image from 'next/image'
import { TbExternalLink } from 'react-icons/tb'
import { IoIosRocket } from 'react-icons/io'
import { BsFillMoonStarsFill }from 'react-icons/bs'
import {FiLinkedin, FiGithub, FiInstagram,} from 'react-icons/fi'
import aryan from '../public/pro.png'
import tedx from '../public/tedx.jpeg'
import sixpm from '../public/sixpm.png'
import { motion } from 'framer-motion'
import { useState } from 'react'
export default function Home() {
  const [darkMode, setDarkMode]  =useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Aryan Adlakha</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="../public.pro.png" /> */}
      </Head>

      <main className='bg-[#151515] px-10 md:px-20 dark:bg-white'>
        <section className = "min-h-screen">
          <nav className='py-10 mb-12 flex justify-between'>
            <a href="#"><h1 className='text-xl text-md text-white dark:text-indigo-800'>aryanadlakha</h1></a>
            <ul className='flex items-center'>
              <li>
                <BsFillMoonStarsFill 
                onClick={()=>setDarkMode(!darkMode)}
                className='cursor-pointer text-2xl text-amber-400 dark:text-indigo-800' />
              </li>
            </ul>
          </nav>
          <div className='text-center p-10'>
            <h2 className='text-7xl py-2 text-[#ffffff] font-medium dark:text-indigo-800'>Aryan Adlakha</h2>
            <h3 className='text-3xl text-white py-2 dark:text-indigo-800'>ML Enthusiast</h3>
            <p className='text-md py-5 leading-8 text-white dark:text-indigo-800  '>
              Computer Science Undergraduate from SRMIST, India. 
              <br />Currently in the most explorative phase of my life.
            </p>
          </div>
          <div className='text-2xl flex justify-center gap-14 text-gray-600 dark:indigo-800'>
            <a href = "https://www.linkedin.com/in/aryan-adlakha-305a04223/"><FiLinkedin color = "cyan-800" /></a>
            <a href = "https://github.com/AryanAdlakha"><FiGithub color = "cyan-800" /></a>
            <a href = "https://www.instagram.com/aryan_adlakha1/"><FiInstagram color = "cyan-800" /></a>
          </div>
          <div className='relative flex justify-center mx-auto'>
            <Image src = {aryan} className = "rounded-full w-80 h-80 mt-20" />
          </div>
        </section>
            {/* <h3 className='text-3xl p-3 mt-5 text-center text-white'>Experience</h3>
        <section className='flex justify-center text-white'>
        <motion.div 
                    whileHover={{ scale: 1.05 }}
                    whileTap={{ scale: 1.05 }}
                    className='h-72 sm:w-[350px] w-[325px] rounded-xl bg-[#242733] xl:m-5 m-3 p-5'>
                    <div className='flex justify-between my-2'>
                      <div className='flex items-center font-semibold text-sm'><IoIosRocket className='h-6 w-6 inline-block mr-2'/>College Club</div>
                      <a href="https://linktr.ee/tedxsrmists"><TbExternalLink className='h-6 w-6 '/></a>
                    </div>
                    <div className='h-3/6'>
                      <div className='flex items-center my-5'>
                        <Image className="h-10 w-10 rounded-xl" src={tedx}/>
                        <div className='text-xl font-semibold mx-2'>Tedx SRMIST</div>
                      </div>
                      <div>September 2020 - Present</div>
                      <div>
                        <ul>
                          <li><b>Member</b></li>
                          <li>Content Development</li>
                        </ul>
                      </div>
                    </div>
                  </motion.div>
                  <motion.div 
                    whileHover={{ scale: 1.05 }}
                    whileTap={{ scale: 1.05 }}
                    className='h-72 sm:w-[350px] w-[325px] rounded-xl bg-[#242733] xl:m-5 m-3 p-5'>
                    <div className='flex justify-between my-2'>
                      <div className='flex items-center font-semibold text-sm'><IoIosRocket className='h-6 w-6 inline-block mr-2'/>College Club</div>
                      <a href="https://linktr.ee/sixpmshow"><TbExternalLink className='h-6 w-6 '/></a>
                    </div>
                    <div className='h-3/6'>
                      <div className='flex items-center my-5'>
                        <Image className="h-10 w-10 rounded-xl" src={sixpm}/>
                        <div className='text-xl font-semibold mx-2'>The Six PM Show</div>
                      </div>
                      <div>September 2020 - Present</div>
                      <div>
                        <ul>
                          <li><b>Technical Associate</b></li>
                          <li></li>
                        </ul>
                      </div>
                    </div>
                  </motion.div>
        </section> */}
      </main>
    </div>
  )
}
